apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twisterlab-archive-pvc
  namespace: twisterlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
