apiVersion: v1
kind: ConfigMap
metadata:
  name: twisterlab-config
  namespace: twisterlab
data:
  n8n_url: "http://192.168.0.30:5678"
---
apiVersion: v1
kind: Secret
metadata:
  name: twisterlab-secrets
  namespace: twisterlab
type: Opaque
stringData:
  n8n_api_key: "VOTRE_CLE_API_N8N_ICI"
