import os
import asyncio
import logging
from datetime import datetime
from twisterlab.agents.real.real_code_review_agent import RealCodeReviewAgent

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

async def run_global_audit(root_path: str):
    print(f"--- Phase 18: Global Repository Audit [{datetime.now().strftime('%Y-%m-%d')}] ---")
    agent = RealCodeReviewAgent()
    all_findings = []
    files_audited = 0
    
    # Target files (.py only, skipping caches and migrations)
    target_exts = [".py"]
    skip_dirs = ["__pycache__", "migrations", ".ipynb_checkpoints"]
    
    for root, dirs, files in os.walk(root_path):
        # Pruning skip dirs for faster traversal
        dirs[:] = [d for d in dirs if d not in skip_dirs]
        
        for file in files:
            if any(file.endswith(ext) for ext in target_exts):
                file_path = os.path.join(root, file)
                rel_path = os.path.relpath(file_path, root_path)
                
                try:
                    with open(file_path, 'r', encoding='utf-8') as f:
                        code = f.read()
                    
                    # Run Orchestrated Audit
                    res = await agent.handle_deep_audit(code, filename=rel_path)
                    
                    if res.success:
                        findings = res.data.get("findings", [])
                        if findings:
                            all_findings.append({
                                "file": rel_path,
                                "count": len(findings),
                                "findings": findings
                            })
                        files_audited += 1
                        if files_audited % 10 == 0:
                            print(f"Audited {files_audited} files...")
                except Exception as e:
                    logger.error(f"Audit: Could not process {rel_path}: {e}")

    # Generate Markdown Report
    report = generate_report(all_findings, files_audited)
    
    # Save to docs
    report_path = os.path.join("docs", "reports", f"global_audit_{datetime.now().strftime('%Y%m%d')}.md")
    os.makedirs(os.path.dirname(report_path), exist_ok=True)
    with open(report_path, "w", encoding="utf-8") as rf:
        rf.write(report)
        
    print(f"\n\u2705 Audit Complete: {files_audited} files scanned.")
    print(f"Report saved to: {report_path}")

def generate_report(results, total_files):
    total_findings = sum(r["count"] for r in results)
    criticals = sum(1 for r in results for f in r["findings"] if f["severity"] == "critical")
    
    lines = [
        f"# TwisterLab Global Audit Report - {datetime.now().strftime('%Y-%m-%d')}",
        "",
        "## Summary",
        f"- **Files Audited**: {total_files}",
        f"- **Issues Detected**: {total_findings}",
        f"- **Critical Hazards**: {criticals}",
        "",
        "## Detailed Findings",
        ""
    ]
    
    for res in results:
        lines.append(f"### ? `{res['file']}` ({res['count']} issues)")
        for f in res["findings"]:
            lines.append(f"- **[{f['agent'].upper()}] {f['severity'].upper()}**: {f['message']}")
            if "remediation" in f:
                lines.append(f"  - *Remediation*: `{f['remediation']}`")
        lines.append("")
        
    lines.append("\n---\n*Generated by TwisterLab CodeReviewOrchestrator v2.0*")
    return "\n".join(lines)

if __name__ == "__main__":
    src_dir = os.path.join(os.getcwd(), "src", "twisterlab")
    asyncio.run(run_global_audit(src_dir))
