"""
Prometheus Metrics for TwisterLab LLM Agents
Exposes performance metrics for monitoring and alerting
"""
from prometheus_client import Counter, Histogram, Gauge, Info
from typing import Optional
from datetime import datetime
from contextlib import contextmanager
import logging

logger = logging.getLogger(__name__)

# ============================================================================
# GENERAL AGENT METRICS (for all autonomous agents)
# ============================================================================

agent_requests_total = Counter(
    'agent_requests_total',
    'Total number of agent execution requests',
    ['agent_name', 'status']  # status: success, failed
)

agent_execution_time_seconds = Histogram(
    'agent_execution_time_seconds',
    'Agent execution time in seconds',
    ['agent_name'],
    buckets=[0.1, 0.5, 1.0, 5.0, 10.0, 30.0, 60.0, 120.0, 300.0]
)

tickets_processed_total = Counter(
    'tickets_processed_total',
    'Total tickets processed by agents',
    ['agent_name', 'status']  # status: success, failed
)

tickets_failed_total = Counter(
    'tickets_failed_total', 
    'Total tickets that failed processing',
    ['agent_name', 'reason']
)

agents_active = Gauge(
    'agents_active',
    'Number of currently active agents',
    ['agent_name']
)


@contextmanager
def track_agent_execution(agent_name: str):
    """Context manager for tracking agent execution metrics"""
    start_time = datetime.now()
    agents_active.labels(agent_name=agent_name).inc()
    
    try:
        yield
        # Success
        agent_requests_total.labels(agent_name=agent_name, status='success').inc()
    except Exception as e:
        # Failure
        agent_requests_total.labels(agent_name=agent_name, status='failed').inc()
        raise
    finally:
        # Always record duration and decrement active count
        duration = (datetime.now() - start_time).total_seconds()
        agent_execution_time_seconds.labels(agent_name=agent_name).observe(duration)
        agents_active.labels(agent_name=agent_name).dec()

# ============================================================================
# CLASSIFIER AGENT METRICS
# ============================================================================

classifier_llm_duration = Histogram(
    'classifier_llm_duration_seconds',
    'Time spent in LLM classification',
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0]
)

classifier_keyword_duration = Histogram(
    'classifier_keyword_duration_seconds',
    'Time spent in keyword classification (fallback)',
    buckets=[0.001, 0.005, 0.01, 0.05, 0.1]
)

classifier_llm_success = Counter(
    'classifier_llm_success_total',
    'Number of successful LLM classifications'
)

classifier_keyword_fallback = Counter(
    'classifier_keyword_fallback_total',
    'Number of times keyword fallback was used'
)

classifier_llm_error = Counter(
    'classifier_llm_error_total',
    'Number of LLM classification errors',
    ['error_type']
)

classifier_confidence = Gauge(
    'classifier_confidence',
    'Classification confidence score',
    ['category']
)

classifier_category_count = Counter(
    'classifier_category_total',
    'Number of tickets classified per category',
    ['category']
)

classifier_llm_tokens = Counter(
    'classifier_llm_tokens_total',
    'Total tokens generated by ClassifierAgent'
)

# ============================================================================
# RESOLVER AGENT METRICS
# ============================================================================

resolver_llm_duration = Histogram(
    'resolver_llm_duration_seconds',
    'Time spent generating SOPs with LLM',
    buckets=[1.0, 5.0, 10.0, 15.0, 30.0, 60.0]
)

resolver_static_duration = Histogram(
    'resolver_static_duration_seconds',
    'Time spent selecting static SOPs (fallback)',
    buckets=[0.01, 0.05, 0.1, 0.5, 1.0]
)

resolver_llm_success = Counter(
    'resolver_llm_success_total',
    'Number of successful LLM SOP generations'
)

resolver_static_fallback = Counter(
    'resolver_static_fallback_total',
    'Number of times static SOP fallback was used'
)

resolver_llm_error = Counter(
    'resolver_llm_error_total',
    'Number of LLM SOP generation errors',
    ['error_type']
)

resolver_sop_steps = Gauge(
    'resolver_sop_steps_count',
    'Number of steps in generated SOP',
    ['sop_type']
)

resolver_llm_tokens = Counter(
    'resolver_llm_tokens_total',
    'Total tokens generated by ResolverAgent'
)

resolver_sop_quality = Histogram(
    'resolver_sop_step_length_chars',
    'Average character length of SOP steps',
    buckets=[20, 40, 60, 80, 100, 150, 200]
)

# ============================================================================
# DESKTOP COMMANDER AGENT METRICS
# ============================================================================

commander_llm_duration = Histogram(
    'commander_llm_duration_seconds',
    'Time spent in LLM command validation',
    buckets=[0.5, 1.0, 2.0, 5.0, 10.0]
)

commander_whitelist_duration = Histogram(
    'commander_whitelist_duration_seconds',
    'Time spent in whitelist validation',
    buckets=[0.0001, 0.001, 0.01, 0.1]
)

commander_llm_validated = Counter(
    'commander_llm_validated_total',
    'Number of commands validated by LLM',
    ['result']  # safe, unsafe
)

commander_whitelist_blocked = Counter(
    'commander_whitelist_blocked_total',
    'Number of commands blocked by whitelist'
)

commander_llm_error = Counter(
    'commander_llm_error_total',
    'Number of LLM validation errors',
    ['error_type']
)

commander_llm_tokens = Counter(
    'commander_llm_tokens_total',
    'Total tokens generated by DesktopCommanderAgent'
)

commander_command_executed = Counter(
    'commander_command_executed_total',
    'Number of commands executed',
    ['command']
)

# ============================================================================
# OLLAMA/GPU METRICS
# ============================================================================

ollama_health = Gauge(
    'ollama_health_status',
    'Ollama service health (1=up, 0=down)'
)

gpu_utilization = Gauge(
    'nvidia_gpu_utilization',
    'GPU utilization percentage',
    ['gpu']
)

gpu_memory_used = Gauge(
    'nvidia_gpu_memory_used_bytes',
    'GPU memory used in bytes',
    ['gpu']
)

gpu_memory_total = Gauge(
    'nvidia_gpu_memory_total_bytes',
    'GPU total memory in bytes',
    ['gpu']
)

gpu_temperature = Gauge(
    'nvidia_gpu_temperature_celsius',
    'GPU temperature in Celsius',
    ['gpu']
)

# ============================================================================
# END-TO-END METRICS
# ============================================================================

ticket_processing_duration = Histogram(
    'ticket_processing_duration_seconds',
    'Total time to process ticket (all agents)',
    buckets=[1.0, 5.0, 10.0, 15.0, 30.0, 60.0, 120.0]
)

ticket_success = Counter(
    'ticket_success_total',
    'Number of successfully processed tickets'
)

ticket_failure = Counter(
    'ticket_failure_total',
    'Number of failed ticket processing',
    ['failure_reason']
)

# ============================================================================
# LLM MODEL INFO
# ============================================================================

llm_model_info = Info(
    'llm_model_info',
    'Information about LLM models in use'
)

# Initialize model info
llm_model_info.info({
    'classifier_model': 'llama3.2:1b',
    'resolver_model': 'llama3.2:1b',
    'commander_model': 'llama3.2:1b',
    'ollama_version': '0.1.0',
    'gpu': 'NVIDIA GeForce GTX 1050',
    'vram_gb': '2'
})


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def record_classifier_llm(duration: float, category: str, confidence: float, tokens: int):
    """Record ClassifierAgent LLM metrics."""
    classifier_llm_duration.observe(duration)
    classifier_llm_success.inc()
    classifier_confidence.labels(category=category).set(confidence)
    classifier_category_count.labels(category=category).inc()
    classifier_llm_tokens.inc(tokens)


def record_classifier_fallback(duration: float, category: str, confidence: float):
    """Record ClassifierAgent keyword fallback metrics."""
    classifier_keyword_duration.observe(duration)
    classifier_keyword_fallback.inc()
    classifier_confidence.labels(category=category).set(confidence)
    classifier_category_count.labels(category=category).inc()


def record_resolver_llm(duration: float, steps_count: int, tokens: int, avg_step_length: float):
    """Record ResolverAgent LLM metrics."""
    resolver_llm_duration.observe(duration)
    resolver_llm_success.inc()
    resolver_sop_steps.labels(sop_type='llm').set(steps_count)
    resolver_llm_tokens.inc(tokens)
    resolver_sop_quality.observe(avg_step_length)


def record_resolver_fallback(duration: float, steps_count: int, sop_name: str):
    """Record ResolverAgent static fallback metrics."""
    resolver_static_duration.observe(duration)
    resolver_static_fallback.inc()
    resolver_sop_steps.labels(sop_type='static').set(steps_count)


def record_commander_llm(duration: float, is_safe: bool, tokens: int):
    """Record DesktopCommanderAgent LLM metrics."""
    commander_llm_duration.observe(duration)
    result = 'safe' if is_safe else 'unsafe'
    commander_llm_validated.labels(result=result).inc()
    commander_llm_tokens.inc(tokens)


def record_commander_whitelist(duration: float, allowed: bool, command: str):
    """Record DesktopCommanderAgent whitelist metrics."""
    commander_whitelist_duration.observe(duration)
    if not allowed:
        commander_whitelist_blocked.inc()
    else:
        commander_command_executed.labels(command=command).inc()


def record_gpu_stats(gpu_id: str, utilization: float, memory_used: int, memory_total: int, temp: float):
    """Record GPU statistics."""
    gpu_utilization.labels(gpu=gpu_id).set(utilization)
    gpu_memory_used.labels(gpu=gpu_id).set(memory_used)
    gpu_memory_total.labels(gpu=gpu_id).set(memory_total)
    gpu_temperature.labels(gpu=gpu_id).set(temp)


def record_ollama_health(is_up: bool):
    """Record Ollama service health."""
    ollama_health.set(1 if is_up else 0)


def record_ticket_processing(duration: float, success: bool, failure_reason: str = None):
    """Record end-to-end ticket processing."""
    ticket_processing_duration.observe(duration)
    if success:
        ticket_success.inc()
    else:
        ticket_failure.labels(failure_reason=failure_reason or 'unknown').inc()


# Export all metrics for easy import
__all__ = [
    # General Agent Metrics
    'agent_requests_total',
    'agent_execution_time_seconds',
    'tickets_processed_total',
    'tickets_failed_total',
    'agents_active',
    'track_agent_execution',
    # Classifier
    'classifier_llm_duration',
    'classifier_keyword_duration',
    'classifier_llm_success',
    'classifier_keyword_fallback',
    'classifier_llm_error',
    'classifier_confidence',
    'classifier_category_count',
    'classifier_llm_tokens',
    # Resolver
    'resolver_llm_duration',
    'resolver_static_duration',
    'resolver_llm_success',
    'resolver_static_fallback',
    'resolver_llm_error',
    'resolver_sop_steps',
    'resolver_llm_tokens',
    'resolver_sop_quality',
    # Commander
    'commander_llm_duration',
    'commander_whitelist_duration',
    'commander_llm_validated',
    'commander_whitelist_blocked',
    'commander_llm_error',
    'commander_llm_tokens',
    'commander_command_executed',
    # GPU/Ollama
    'ollama_health',
    'gpu_utilization',
    'gpu_memory_used',
    'gpu_memory_total',
    'gpu_temperature',
    # End-to-end
    'ticket_processing_duration',
    'ticket_success',
    'ticket_failure',
    # Helpers
    'record_classifier_llm',
    'record_classifier_fallback',
    'record_resolver_llm',
    'record_resolver_fallback',
    'record_commander_llm',
    'record_commander_whitelist',
    'record_gpu_stats',
    'record_ollama_health',
    'record_ticket_processing',
]
