"""
TwisterLab Trading Database Models
Phase 5-C: Performance Journaling & Paper Trading
"""

from __future__ import annotations
from datetime import datetime, timezone
from typing import Optional
from sqlalchemy import String, Text, Float, DateTime, ForeignKey, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship
from ..session import Base

class TradingSignalRecord(Base):
    """Logs every trading signal generated by the agent."""
    __tablename__ = "trading_signals"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=lambda: datetime.now(timezone.utc))
    symbol: Mapped[str] = mapped_column(String(20), index=True)
    timeframe: Mapped[str] = mapped_column(String(10))
    strategy_name: Mapped[str] = mapped_column(String(50), index=True)
    direction: Mapped[str] = mapped_column(String(10)) # LONG, SHORT, NO_TRADE
    confidence: Mapped[float] = mapped_column(Float)
    entry_price: Mapped[float] = mapped_column(Float)
    stop_loss: Mapped[float] = mapped_column(Float)
    take_profit: Mapped[float] = mapped_column(Float)
    atr: Mapped[float] = mapped_column(Float)
    rationale: Mapped[str] = mapped_column(Text)
    indicator_data: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    status: Mapped[str] = mapped_column(String(20), default="generated") # generated, ignored, traded

    # Relationship to paper trades
    trades: Mapped[list["PaperTradeRecord"]] = relationship(back_populates="signal", cascade="all, delete-orphan")

class PaperTradeRecord(Base):
    """Tracks simulated (paper) trades linked to a signal."""
    __tablename__ = "paper_trades"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    signal_id: Mapped[int] = mapped_column(ForeignKey("trading_signals.id"), index=True)
    opened_at: Mapped[datetime] = mapped_column(DateTime, default=lambda: datetime.now(timezone.utc))
    closed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    
    symbol: Mapped[str] = mapped_column(String(20))
    strategy_name: Mapped[str] = mapped_column(String(50))
    side: Mapped[str] = mapped_column(String(10)) # LONG, SHORT
    
    entry_price_planned: Mapped[float] = mapped_column(Float)
    entry_price_filled: Mapped[float] = mapped_column(Float) # Inc. slippage
    stop_loss: Mapped[float] = mapped_column(Float)
    take_profit: Mapped[float] = mapped_column(Float)
    exit_price: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    
    exit_reason: Mapped[Optional[str]] = mapped_column(String(50), nullable=True) # tp_hit, sl_hit, manual, timeout
    status: Mapped[str] = mapped_column(String(20), default="open") # open, closed
    
    # Costs & Performance
    fee_cost: Mapped[float] = mapped_column(Float, default=0.0)
    slippage_cost: Mapped[float] = mapped_column(Float, default=0.0)
    gross_pnl: Mapped[float] = mapped_column(Float, default=0.0)
    net_pnl: Mapped[float] = mapped_column(Float, default=0.0)
    r_multiple: Mapped[float] = mapped_column(Float, default=0.0)
    
    # Relationship to signal
    signal: Mapped["TradingSignalRecord"] = relationship(back_populates="trades")

class LiveOrderRecord(Base):
    """Tracks real broker orders and their lifecycle."""
    __tablename__ = "live_orders"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    signal_id: Mapped[Optional[int]] = mapped_column(ForeignKey("trading_signals.id"), nullable=True)
    exchange_id: Mapped[Optional[str]] = mapped_column(String(100), index=True) # Order ID on exchange
    request_id: Mapped[Optional[str]] = mapped_column(String(100), index=True, nullable=True) # Idempotency key from Maestro
    
    symbol: Mapped[str] = mapped_column(String(20), index=True)
    strategy_name: Mapped[Optional[str]] = mapped_column(String(50), index=True, nullable=True) # Added for Phase 9
    side: Mapped[str] = mapped_column(String(10)) # BUY, SELL
    order_type: Mapped[str] = mapped_column(String(20), default="market")
    
    amount: Mapped[float] = mapped_column(Float)
    price_requested: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    price_filled: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    
    # Risk Management (Phase 7)
    stop_loss: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    take_profit: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    trailing_sl_trigger: Mapped[Optional[float]] = mapped_column(Float, nullable=True) # Price to activate TSL
    trailing_sl_distance: Mapped[Optional[float]] = mapped_column(Float, nullable=True) # Distance from peak
    highest_price_observed: Mapped[Optional[float]] = mapped_column(Float, nullable=True) # Peak for TSL
    atr_at_entry: Mapped[Optional[float]] = mapped_column(Float, nullable=True) # ATR for adaptive distance
    
    # Telemetry (Phase 9A)
    exit_price: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    exit_reason: Mapped[Optional[str]] = mapped_column(String(50), nullable=True) # sl_hit, tp_hit, tsl_hit, manual, halt
    realized_pnl: Mapped[Optional[float]] = mapped_column(Float, nullable=True) # USD
    realized_pnl_pct: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    
    status: Mapped[str] = mapped_column(String(20), default="pending") # pending, submitted, open, filled, canceled, rejected
    is_active: Mapped[bool] = mapped_column(default=False) # True if position is currently open
    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))
    closed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)

class ExecutionAuditLog(Base):
    """Immutable log of every exchange API request and its outcome."""
    __tablename__ = "execution_audit"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    timestamp: Mapped[datetime] = mapped_column(DateTime, default=lambda: datetime.now(timezone.utc))
    
    action: Mapped[str] = mapped_column(String(50)) # create_order, cancel_order, fetch_balance
    request_data: Mapped[str] = mapped_column(Text) # JSON string
    response_data: Mapped[Optional[str]] = mapped_column(Text, nullable=True) # JSON string
    
    status: Mapped[str] = mapped_column(String(20)) # success, error
    latency_ms: Mapped[Optional[int]] = mapped_column(Float, nullable=True)
