apiVersion: v1
kind: Secret
metadata:
  name: twisterlab-secrets-v4
  namespace: twisterlab
type: Opaque
stringData:
  # core
  CORE__SECRET_KEY: "change-me-in-production"
  CORE__JWT_SECRET_KEY: "change-me-in-production"
  
  # infra
  INFRA__POSTGRES_USER: "twisterlab"
  INFRA__POSTGRES_PASSWORD: "twisterlab_password"
  INFRA__REDIS_PASSWORD: ""
  INFRA__N8N_API_KEY: ""
  INFRA__NOTION_TOKEN: ""
  INFRA__NOTION_DEFAULT_DATABASE_ID: ""
